"""nitial tables

Revision ID: 6b3af28ea24a
Revises: 
Create Date: 2024-05-09 21:35:15.671475

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b3af28ea24a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content",
        sa.Column("content_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("content_id"),
    )
    op.create_table(
        "notification_schedule",
        sa.Column("schedule_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("schedule_id"),
    )
    op.create_table(
        "notifications",
        sa.Column("notification_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("content_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "recipient_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("schedule_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.content_id"],
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["notification_schedule.schedule_id"],
        ),
        sa.PrimaryKeyConstraint("notification_id"),
    )
    op.create_table(
        "notification_history",
        sa.Column("history_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("notification_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.notification_id"],
        ),
        sa.PrimaryKeyConstraint("history_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_history")
    op.drop_table("notifications")
    op.drop_table("notification_schedule")
    op.drop_table("content")
    # ### end Alembic commands ###
