"""add text

Revision ID: 7c827a168aec
Revises: 6b3af28ea24a
Create Date: 2024-05-20 05:03:22.295031

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c827a168aec"
down_revision: Union[str, None] = "6b3af28ea24a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("notifications", "text")
    # ### end Alembic commands ###
